models:
  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    base_url: https://openrouter.ai/api/v1
    api_key: "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"
    default_headers: {}
    total: 128000
    max_new_tokens: 16384
  deepseek-coder-33b-instruct:
    model_id: deepseek-ai/deepseek-coder-33b-instruct
    base_url: "PASTE YOUR MODEL ENDPOINT HERE"
    api_key: "PASTE YOUR API KEY HERE, IF REQUIRED"
    default_headers: {}
    total: 16384
    max_new_tokens: 4096
